import 'package:hive_flutter/hive_flutter.dart';
import '../models/cart_item_model.dart';
import '../models/address_model.dart';
import '../models/payment_method_model.dart';
import '../models/user_model.dart';
import '../models/product_model.dart';

class StorageService {
  static const String _cartBox = 'cart_box';
  static const String _addressBox = 'address_box';
  static const String _paymentBox = 'payment_box';
  static const String _userBox = 'user_box';
  static const String _authBox = 'auth_box';
  static const String _favoritesBox = 'favorites_box';

  // Initialize Hive
  static Future<void> init() async {
    await Hive.initFlutter();
    
    // Register adapters (generated by build_runner)
    // Register ProductModel and RatingModel first (they are used by CartItemModel)
    Hive.registerAdapter(ProductModelAdapter());
    Hive.registerAdapter(RatingModelAdapter());
    
    // Register other adapters
    Hive.registerAdapter(CartItemModelAdapter());
    Hive.registerAdapter(AddressModelAdapter());
    Hive.registerAdapter(PaymentMethodModelAdapter());
    Hive.registerAdapter(UserModelAdapter());

    // Open boxes
    await Hive.openBox<CartItemModel>(_cartBox);
    await Hive.openBox<AddressModel>(_addressBox);
    await Hive.openBox<PaymentMethodModel>(_paymentBox);
    await Hive.openBox<UserModel>(_userBox);
    await Hive.openBox(_authBox);
    await Hive.openBox<int>(_favoritesBox);
  }

  // Cart operations
  Box<CartItemModel> get _cartBoxInstance => Hive.box<CartItemModel>(_cartBox);

  Future<void> addToCart(CartItemModel item) async {
    await _cartBoxInstance.put(item.id, item);
  }

  Future<void> removeFromCart(String itemId) async {
    await _cartBoxInstance.delete(itemId);
  }

  Future<void> updateCartItem(CartItemModel item) async {
    await _cartBoxInstance.put(item.id, item);
  }

  Future<void> clearCart() async {
    await _cartBoxInstance.clear();
  }

  List<CartItemModel> getCartItems() {
    return _cartBoxInstance.values.toList();
  }

  // Address operations
  Box<AddressModel> get _addressBoxInstance => Hive.box<AddressModel>(_addressBox);

  Future<void> saveAddress(AddressModel address) async {
    // If this address is default, update others
    if (address.isDefault) {
      final addresses = _addressBoxInstance.values.toList();
      for (var addr in addresses) {
        if (addr.id != address.id && addr.isDefault) {
          await _addressBoxInstance.put(
            addr.id,
            addr.copyWith(isDefault: false),
          );
        }
      }
    }
    await _addressBoxInstance.put(address.id, address);
  }

  Future<void> deleteAddress(String addressId) async {
    await _addressBoxInstance.delete(addressId);
  }

  List<AddressModel> getAddresses() {
    return _addressBoxInstance.values.toList();
  }

  AddressModel? getDefaultAddress() {
    return _addressBoxInstance.values.firstWhere(
      (address) => address.isDefault,
      orElse: () => _addressBoxInstance.values.isNotEmpty
          ? _addressBoxInstance.values.first
          : throw Exception('No addresses found'),
    );
  }

  // Payment operations
  Box<PaymentMethodModel> get _paymentBoxInstance =>
      Hive.box<PaymentMethodModel>(_paymentBox);

  Future<void> savePaymentMethod(PaymentMethodModel payment) async {
    // If this payment is default, update others
    if (payment.isDefault) {
      final payments = _paymentBoxInstance.values.toList();
      for (var pm in payments) {
        if (pm.id != payment.id && pm.isDefault) {
          await _paymentBoxInstance.put(
            pm.id,
            pm.copyWith(isDefault: false),
          );
        }
      }
    }
    await _paymentBoxInstance.put(payment.id, payment);
  }

  Future<void> deletePaymentMethod(String paymentId) async {
    await _paymentBoxInstance.delete(paymentId);
  }

  List<PaymentMethodModel> getPaymentMethods() {
    return _paymentBoxInstance.values.toList();
  }

  PaymentMethodModel? getDefaultPaymentMethod() {
    try {
      return _paymentBoxInstance.values.firstWhere(
        (PaymentMethodModel payment) => payment.isDefault,
        orElse: () => _paymentBoxInstance.values.isNotEmpty
            ? _paymentBoxInstance.values.first
            : throw Exception('No payment methods found'),
      );
    } catch (e) {
      return null;
    }
  }

  // User operations
  Box<UserModel> get _userBoxInstance => Hive.box<UserModel>(_userBox);

  Future<void> saveUser(UserModel user) async {
    await _userBoxInstance.put('current_user', user);
  }

  UserModel? getUser() {
    return _userBoxInstance.get('current_user');
  }

  Future<void> deleteUser() async {
    await _userBoxInstance.delete('current_user');
  }

  // Auth operations
  Box get _authBoxInstance => Hive.box(_authBox);

  Future<void> saveAuthToken(String token) async {
    await _authBoxInstance.put('auth_token', token);
  }

  String? getAuthToken() {
    return _authBoxInstance.get('auth_token');
  }

  Future<void> deleteAuthToken() async {
    await _authBoxInstance.delete('auth_token');
  }

  Future<void> saveRememberMe(bool value) async {
    await _authBoxInstance.put('remember_me', value);
  }

  bool getRememberMe() {
    return _authBoxInstance.get('remember_me', defaultValue: false);
  }

  // Favorites operations
  Box<int> get _favoritesBoxInstance => Hive.box<int>(_favoritesBox);

  Future<void> addFavorite(int productId) async {
    await _favoritesBoxInstance.put(productId, productId);
  }

  Future<void> removeFavorite(int productId) async {
    await _favoritesBoxInstance.delete(productId);
  }

  List<int> getFavoriteIds() {
    return _favoritesBoxInstance.values.toList();
  }

  bool isFavorite(int productId) {
    return _favoritesBoxInstance.containsKey(productId);
  }

  Future<void> clearFavorites() async {
    await _favoritesBoxInstance.clear();
  }

  // Clear all data
  Future<void> clearAll() async {
    await _cartBoxInstance.clear();
    await _addressBoxInstance.clear();
    await _paymentBoxInstance.clear();
    await _userBoxInstance.clear();
    await _authBoxInstance.clear();
    await _favoritesBoxInstance.clear();
  }
}
